# Generated by Django 2.2 on 2020-12-23 17:54

import daily_inspection.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plugin.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('people', 'People'), ('machine', 'Machine'), ('device', 'Device'), ('method', 'Method'), ('environment', 'Environment')], default='device', max_length=30, verbose_name='Category')),
                ('inspection_content', models.CharField(max_length=30, verbose_name='Inspection Content')),
                ('impact', models.CharField(max_length=30, verbose_name='Impact')),
                ('rectification_measures', models.TextField(max_length=500, verbose_name='Rectification Measures')),
                ('rectification_status', models.CharField(choices=[('completed', 'Completed'), ('uncompleted', 'Uncompleted')], default='uncompleted', max_length=30, verbose_name='Rectification Status')),
                ('owner', models.CharField(max_length=30, verbose_name='Owner')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Inspection Created Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Inspection Updated Date')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='rectification completed time')),
                ('image_before', plugin.fields.ThumbnailImageField(null=True, upload_to=daily_inspection.models.image_upload_to_dailyinspection, verbose_name='Picture before Rectification')),
                ('image_after', models.ImageField(blank=True, null=True, upload_to=daily_inspection.models.image_upload_to_dailyinspection, verbose_name='Picture after Rectification')),
                ('location', models.CharField(choices=[('1', 'Storage Area'), ('2', 'Loading Unloading Area'), ('3', 'Vehicle Inspection Area'), ('4', 'Office Area'), ('5', 'Stock Up Area'), ('6', 'Damaged Area'), ('7', 'Packing Area'), ('8', 'Forklift Charging Area')], default='1', max_length=30, verbose_name='Location')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Inspector')),
            ],
            options={
                'verbose_name_plural': 'Daily Inspection',
                'ordering': ['-created'],
                'verbose_name': 'Daily Inspection',
            },
        ),
        migrations.CreateModel(
            name='DailyInspectionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=300, verbose_name='log')),
                ('dailyinspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_inspection.DailyInspection', verbose_name='Daily Inspection')),
            ],
        ),
    ]
