# Generated by Django 2.2 on 2020-12-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinspection',
            name='trigger_method',
            field=models.CharField(choices=[('people', 'People'), ('ai', 'AI')], default='people', max_length=30, verbose_name='trigger method'),
        ),
    ]
