# Generated by Django 2.2 on 2020-08-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Type',
            },
        ),
        migrations.CreateModel(
            name='EquipmentInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_condition', models.CharField(choices=[('normal', 'Normal'), ('breakdown', 'Breakdown')], default='normal', max_length=30, verbose_name='Use Condition')),
                ('inspector', models.CharField(max_length=30, verbose_name='Inspector')),
                ('owner', models.CharField(blank=True, max_length=30, null=True, verbose_name='Owner')),
                ('comments', models.TextField(blank=True, max_length=130, null=True, verbose_name='Comments')),
                ('check_date', models.DateField(auto_now_add=True, verbose_name='Date of Inspection')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Latest Update')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='rectification completed time')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.Equipment', verbose_name='Equipment')),
            ],
            options={
                'verbose_name': 'Equipment Inspection',
                'verbose_name_plural': 'Equipment Inspection',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.EquipmentType', verbose_name='Type'),
        ),
    ]
